=== SamoilenkoVladimir/training-task3/deposits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/deposits" xmlns:tns="http://www.example.org/deposits" elementFormDefault="qualified">
	<element name="deposits">
		<complexType>
			<sequence>
				<element name="deposit" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="name" type="string"/>
							<element name="country" type="string"/>
							<element name="type" >
								<simpleType>
									<restriction base="string">
										<enumeration value="довостребования"></enumeration>
										<enumeration value="срочный"></enumeration>
										<enumeration value="расчетный"></enumeration>
										<enumeration value="накопительный"></enumeration>
										<enumeration value="сберегательный"></enumeration>
									</restriction>
								</simpleType>
							</element>
							<element name="depositor">
								<complexType>
									<sequence>
										<element name="depositor-name" type="string"/>
										<element name="depositor-surname" type="string"/>
									</sequence>
								</complexType>
							</element>
							<element name="account-id" >
								<simpleType>
									<restriction base="positiveInteger">
										<pattern value="\d{13}">
										</pattern>
									</restriction>
								</simpleType>
							</element>
							<element name="amount-on-deposit" >
								<simpleType>
									<restriction base="positiveInteger">
										<minInclusive value="1" />
									</restriction>
								</simpleType>
							</element>
							<element name="profitability" type="byte"/>
							<element name="time-constraints" type="positiveInteger" minOccurs="0"/>						
							</sequence>
						<attribute name="id" type="string" use="required"/>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== SamoilenkoVladimir/training-task3/NEWdeposits.xml
<?xml version="1.0" encoding="UTF-8"?><deposits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/deposits" xsi:schemaLocation="http://www.example.org/deposits deposits.xsd"><deposit id="d2"><name>UBS</name><country>Швейцария</country><type>срочный</type><depositor><depositor-name>Василий</depositor-name><depositor-surname>Петров</depositor-surname></depositor><account-id>3014000003322</account-id><amount-on-deposit>80010</amount-on-deposit><profitability>5</profitability><time-constraints>180</time-constraints></deposit><deposit id="d1"><name>Беларусбанк</name><country>Беларусь</country><type>довостребования</type><depositor><depositor-name>Иван</depositor-name><depositor-surname>Иванов</depositor-surname></depositor><account-id>3014000001234</account-id><amount-on-deposit>50009</amount-on-deposit><profitability>7</profitability><time-constraints>365</time-constraints></deposit><deposit id="d3"><name>Сбер</name><country>Россия</country><type>расчетный</type><depositor><depositor-name>Дональд</depositor-name><depositor-surname>Трамп</depositor-surname></depositor><account-id>3014000004567</account-id><amount-on-deposit>20001</amount-on-deposit><profitability>2</profitability></deposit></deposits>
